language: python
dist: xenial
services:
  - xvfb

addons:
  chrome: stable
  apt:
    packages:
      - xvfb
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - 'export DISPLAY=:99.0'
  - 'export TRAVIS=true'
  - 'export DEBUG=true'

script:
  - coverage run tests/test.py

after_success:
  - codecov