language: python
dist: xenial
services:
  - xvfb

addons:
  chrome: stable
  apt:
    packages:
      - xvfb
python:
  - "3.7"
install:
  - pip install -r requirements.txt

before_script:
  - 'export DISPLAY=:99.0'
  - 'export TRAVIS=true'
  - 'export DEBUG=true'

script:
  - python -m unittest tests.test

after_success:
  - bash <(curl -s https://codecov.io/bash)